#!/bin/sh

# Some helper functions for simpler session files
kill_window() { tmux kill-window -t $session:"$@"; }
new_session() { tmux new-session -d -s $session "$@"; }
new_window() { tmux new-window -d -c $PWD -t $session "$@"; }
select_pane() { tmux select-pane -t $session:"$@"; }
select_window() { tmux select-window -t $session:"$@"; }
send_keys() { tmux send-keys -t $session:"$@"; }
set_env() { tmux set-environment -t $session "$@"; }
set_path() { tmux set-option -t $session default-path "$@"; }
split() { tmux split-window -t $session:"$@"; }
swap() { tmux swap-pane -t $session:"$@"; }


# Print usage information if there's not exactly 1 argument
usage() { echo "Usage: $0 tmux-session"; }
[ $# -ne 1 ] && usage && exit 1

session=$1
sessiondir=${TMUXSTART_DIR:-$HOME/.tmuxstart}
TMUX_OLD=$TMUX
TMUX=
if ! tmux has-session -t $session ; then
    if [ -f "$sessiondir/$1" ] ; then
        . "$sessiondir/$1"
    else
        tmux new-session -d -s $session
    fi
fi
if [ "$TMUX_OLD" = "" ]; then
    tmux attach-session -t $session
else
    tmux switch-client -t $session
fi
TMUX=$TMUX_OLD
